/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elli.shop;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ACER
 */
public class laporan extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    public laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        roundedPanel1 = new org.hq.RoundedPanel();
        jLabel9 = new javax.swing.JLabel();
        labeltrans7 = new javax.swing.JLabel();
        labeltrans1 = new javax.swing.JLabel();
        labeltrans10 = new javax.swing.JLabel();
        labeltrans11 = new javax.swing.JLabel();
        labeltrans12 = new javax.swing.JLabel();
        labeltrans13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        paneldasbor = new org.hq.RoundedPanel();
        paneltransaksi = new org.hq.RoundedPanel();
        panellap = new org.hq.RoundedPanel();
        panelsup = new org.hq.RoundedPanel();
        panelkrwn = new org.hq.RoundedPanel();
        panelbrg = new org.hq.RoundedPanel();
        panellogout = new org.hq.RoundedPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        roundedPanel2 = new org.hq.RoundedPanel();
        roundedPanel3 = new org.hq.RoundedPanel();
        jPanel3 = new javax.swing.JPanel();
        panelpenju = new org.hq.RoundedPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelbeli = new org.hq.RoundedPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 87, 118));
        jPanel1.setPreferredSize(new java.awt.Dimension(181, 635));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(0, 87, 118));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("MAIN  MENU");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 121, 139, 30));

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setRoundBottomLeft(20);
        roundedPanel1.setRoundBottomRight(20);
        roundedPanel1.setRoundTopLeft(20);
        roundedPanel1.setRoundTopRight(20);
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 87, 118));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\top_menu_48px.png")); // NOI18N
        roundedPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labeltrans7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labeltrans7.setForeground(new java.awt.Color(0, 87, 118));
        labeltrans7.setText("DASHBOARD");
        labeltrans7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labeltrans7MouseMoved(evt);
            }
        });
        labeltrans7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans7MouseExited(evt);
            }
        });
        roundedPanel1.add(labeltrans7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        labeltrans1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labeltrans1.setForeground(new java.awt.Color(0, 78, 118));
        labeltrans1.setText("TRANSAKSI");
        labeltrans1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labeltrans1MouseMoved(evt);
            }
        });
        labeltrans1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans1MouseExited(evt);
            }
        });
        roundedPanel1.add(labeltrans1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        labeltrans10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labeltrans10.setForeground(new java.awt.Color(252, 249, 137));
        labeltrans10.setText("LAPORAN");
        labeltrans10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans10MouseExited(evt);
            }
        });
        roundedPanel1.add(labeltrans10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        labeltrans11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labeltrans11.setForeground(new java.awt.Color(0, 78, 118));
        labeltrans11.setText("DATA SUPPLIER");
        labeltrans11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labeltrans11MouseMoved(evt);
            }
        });
        labeltrans11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans11MouseExited(evt);
            }
        });
        roundedPanel1.add(labeltrans11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        labeltrans12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labeltrans12.setForeground(new java.awt.Color(0, 78, 118));
        labeltrans12.setText("DATA KARYAWAN");
        labeltrans12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labeltrans12MouseMoved(evt);
            }
        });
        labeltrans12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans12MouseExited(evt);
            }
        });
        roundedPanel1.add(labeltrans12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        labeltrans13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labeltrans13.setForeground(new java.awt.Color(0, 78, 118));
        labeltrans13.setText("DATA BARANG");
        labeltrans13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labeltrans13MouseMoved(evt);
            }
        });
        labeltrans13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltrans13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeltrans13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeltrans13MouseExited(evt);
            }
        });
        roundedPanel1.add(labeltrans13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 87, 118));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\logoutnew().png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        roundedPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        paneldasbor.setBackground(new java.awt.Color(255, 255, 255));
        paneldasbor.setRoundBottomRight(20);
        paneldasbor.setRoundTopRight(20);

        javax.swing.GroupLayout paneldasborLayout = new javax.swing.GroupLayout(paneldasbor);
        paneldasbor.setLayout(paneldasborLayout);
        paneldasborLayout.setHorizontalGroup(
            paneldasborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        paneldasborLayout.setVerticalGroup(
            paneldasborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        roundedPanel1.add(paneldasbor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 140, 20));

        paneltransaksi.setBackground(new java.awt.Color(255, 255, 255));
        paneltransaksi.setRoundBottomRight(20);
        paneltransaksi.setRoundTopRight(20);

        javax.swing.GroupLayout paneltransaksiLayout = new javax.swing.GroupLayout(paneltransaksi);
        paneltransaksi.setLayout(paneltransaksiLayout);
        paneltransaksiLayout.setHorizontalGroup(
            paneltransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        paneltransaksiLayout.setVerticalGroup(
            paneltransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        roundedPanel1.add(paneltransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        panellap.setBackground(new java.awt.Color(0, 87, 118));
        panellap.setRoundBottomRight(20);
        panellap.setRoundTopRight(20);

        javax.swing.GroupLayout panellapLayout = new javax.swing.GroupLayout(panellap);
        panellap.setLayout(panellapLayout);
        panellapLayout.setHorizontalGroup(
            panellapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        panellapLayout.setVerticalGroup(
            panellapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        roundedPanel1.add(panellap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        panelsup.setBackground(new java.awt.Color(255, 255, 255));
        panelsup.setRoundBottomRight(20);
        panelsup.setRoundTopRight(20);

        javax.swing.GroupLayout panelsupLayout = new javax.swing.GroupLayout(panelsup);
        panelsup.setLayout(panelsupLayout);
        panelsupLayout.setHorizontalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        panelsupLayout.setVerticalGroup(
            panelsupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        roundedPanel1.add(panelsup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        panelkrwn.setBackground(new java.awt.Color(255, 255, 255));
        panelkrwn.setRoundBottomRight(20);
        panelkrwn.setRoundTopRight(20);

        javax.swing.GroupLayout panelkrwnLayout = new javax.swing.GroupLayout(panelkrwn);
        panelkrwn.setLayout(panelkrwnLayout);
        panelkrwnLayout.setHorizontalGroup(
            panelkrwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        panelkrwnLayout.setVerticalGroup(
            panelkrwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        roundedPanel1.add(panelkrwn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        panelbrg.setBackground(new java.awt.Color(255, 255, 255));
        panelbrg.setRoundBottomRight(20);
        panelbrg.setRoundTopRight(20);

        javax.swing.GroupLayout panelbrgLayout = new javax.swing.GroupLayout(panelbrg);
        panelbrg.setLayout(panelbrgLayout);
        panelbrgLayout.setHorizontalGroup(
            panelbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        panelbrgLayout.setVerticalGroup(
            panelbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        roundedPanel1.add(panelbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        panellogout.setBackground(new java.awt.Color(0, 87, 118));
        panellogout.setRoundBottomLeft(20);
        panellogout.setRoundTopRight(20);
        panellogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 87, 118));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\logoutnew().png")); // NOI18N
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel8MouseMoved(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        panellogout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 40, 40));

        roundedPanel1.add(panellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 40, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 87, 118));
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\squared_menu_48px.png")); // NOI18N
        roundedPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 138, -1, 40));

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 470));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\iconnew-min (1).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 87, 118));
        jLabel4.setText("LAPORAN");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 6, 180, 50));

        roundedPanel2.setBackground(new java.awt.Color(0, 87, 118));
        roundedPanel2.setRoundBottomLeft(20);
        roundedPanel2.setRoundBottomRight(20);
        roundedPanel2.setRoundTopLeft(20);
        roundedPanel2.setRoundTopRight(20);

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(roundedPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 730, 10));

        roundedPanel3.setBackground(new java.awt.Color(252, 249, 137));
        roundedPanel3.setRoundBottomLeft(20);
        roundedPanel3.setRoundBottomRight(20);
        roundedPanel3.setRoundTopLeft(20);
        roundedPanel3.setRoundTopRight(20);

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(roundedPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 730, 10));

        jPanel3.setBackground(new java.awt.Color(0, 87, 118));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelpenju.setBackground(new java.awt.Color(255, 200, 78));
        panelpenju.setRoundBottomRight(50);
        panelpenju.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelpenjuMouseMoved(evt);
            }
        });
        panelpenju.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelpenjuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelpenjuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelpenjuMouseExited(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("  LAPORAN");
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel13MouseMoved(evt);
            }
        });
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("  PENJUALAN");
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelpenjuLayout = new javax.swing.GroupLayout(panelpenju);
        panelpenju.setLayout(panelpenjuLayout);
        panelpenjuLayout.setHorizontalGroup(
            panelpenjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(panelpenjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelpenjuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panelpenjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelpenjuLayout.setVerticalGroup(
            panelpenjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(panelpenjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelpenjuLayout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addGroup(panelpenjuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelpenjuLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 10, Short.MAX_VALUE)))
        );

        jPanel3.add(panelpenju, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, 110));

        panelbeli.setBackground(new java.awt.Color(23, 176, 151));
        panelbeli.setRoundBottomRight(50);
        panelbeli.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelbeliMouseMoved(evt);
            }
        });
        panelbeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelbeliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelbeliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelbeliMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("  LAPORAN");
        jLabel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel15MouseMoved(evt);
            }
        });
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("  PEMBELIAN");
        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel12MouseMoved(evt);
            }
        });
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelbeliLayout = new javax.swing.GroupLayout(panelbeli);
        panelbeli.setLayout(panelbeliLayout);
        panelbeliLayout.setHorizontalGroup(
            panelbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(panelbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelbeliLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panelbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelbeliLayout.setVerticalGroup(
            panelbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(panelbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelbeliLayout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addGroup(panelbeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelbeliLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 10, Short.MAX_VALUE)))
        );

        jPanel3.add(panelbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 180, 110));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 180, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 140, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, 10));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 180, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 140, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, 10));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 730, 530));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 750, 640));

        setSize(new java.awt.Dimension(930, 631));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labeltrans7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans7MouseClicked
        try {
            Dashboard2 das = new Dashboard2();
            das.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(transaksi2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labeltrans7MouseClicked

    private void labeltrans7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans7MouseEntered
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        labeltrans7.setForeground(randomColor);
        paneldasbor.setBackground(randomColor2);
    }//GEN-LAST:event_labeltrans7MouseEntered

    private void labeltrans7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans7MouseExited
        Color randomColor2 = new Color(0, 87, 118);

        labeltrans7.setForeground(randomColor2);
        paneldasbor.setBackground(Color.white);
    }//GEN-LAST:event_labeltrans7MouseExited

    private void labeltrans1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseClicked
        transaksi2 t = new transaksi2();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans1MouseClicked

    private void labeltrans1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseEntered
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        labeltrans1.setForeground(randomColor);
        paneltransaksi.setBackground(randomColor2);
    }//GEN-LAST:event_labeltrans1MouseEntered

    private void labeltrans1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseExited
        Color randomColor2 = new Color(0, 87, 118);

        labeltrans1.setForeground(randomColor2);
        paneltransaksi.setBackground(Color.white);
    }//GEN-LAST:event_labeltrans1MouseExited

    private void labeltrans10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans10MouseClicked

    }//GEN-LAST:event_labeltrans10MouseClicked

    private void labeltrans10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans10MouseEntered

    }//GEN-LAST:event_labeltrans10MouseEntered

    private void labeltrans10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans10MouseExited

    }//GEN-LAST:event_labeltrans10MouseExited

    private void labeltrans11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans11MouseClicked
        supplier plier = new supplier();
        plier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans11MouseClicked

    private void labeltrans11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans11MouseEntered
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        labeltrans11.setForeground(randomColor);
        panelsup.setBackground(randomColor2);
    }//GEN-LAST:event_labeltrans11MouseEntered

    private void labeltrans11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans11MouseExited
        Color randomColor2 = new Color(0, 87, 118);

        labeltrans11.setForeground(randomColor2);
        panelsup.setBackground(Color.white);
    }//GEN-LAST:event_labeltrans11MouseExited

    private void labeltrans12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans12MouseClicked
        karyawan2 wan = new karyawan2();
        wan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labeltrans12MouseClicked

    private void labeltrans12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans12MouseEntered
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        labeltrans12.setForeground(randomColor);
        panelkrwn.setBackground(randomColor2);
    }//GEN-LAST:event_labeltrans12MouseEntered

    private void labeltrans12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans12MouseExited
        Color randomColor2 = new Color(0, 87, 118);

        labeltrans12.setForeground(randomColor2);
        panelkrwn.setBackground(Color.white);
    }//GEN-LAST:event_labeltrans12MouseExited

    private void labeltrans13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans13MouseClicked

        try {
            barang2 rang = new barang2();
            rang.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_labeltrans13MouseClicked

    private void labeltrans13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans13MouseEntered
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        labeltrans13.setForeground(randomColor);
        panelbrg.setBackground(randomColor2);
    }//GEN-LAST:event_labeltrans13MouseEntered

    private void labeltrans13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans13MouseExited
        Color randomColor2 = new Color(0, 87, 118);

        labeltrans13.setForeground(randomColor2);
        panelbrg.setBackground(Color.white);
    }//GEN-LAST:event_labeltrans13MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Login2 gin = new Login2();
        gin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        panellogout.setBackground(Color.red);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        Color randomColor2 = new Color(0, 87, 118);
        panellogout.setBackground(randomColor2);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        opsi_login gin = new opsi_login();
        gin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        panellogout.setBackground(Color.red);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        Color randomColor2 = new Color(0, 87, 118);
        panellogout.setBackground(randomColor2);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        laporan_jual al = new laporan_jual();
        al.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        Color randomColor = new Color(255, 200, 78);

        jLabel13.setForeground(randomColor);
        jLabel10.setForeground(randomColor);
        panelpenju.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        Color randomColor2 = new Color(255, 200, 78);

        jLabel13.setForeground(Color.WHITE);
        jLabel10.setForeground(Color.WHITE);
        panelpenju.setBackground(randomColor2);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        laporan_jual al = new laporan_jual();
        al.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        Color randomColor = new Color(255, 200, 78);

        jLabel10.setForeground(randomColor);
        jLabel13.setForeground(randomColor);
        panelpenju.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        Color randomColor2 = new Color(255, 200, 78);

        jLabel10.setForeground(Color.WHITE);
        jLabel13.setForeground(Color.WHITE);
        panelpenju.setBackground(randomColor2);
    }//GEN-LAST:event_jLabel10MouseExited

    private void panelpenjuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelpenjuMouseClicked
        try {
            // TODO add your handling code here:
            transaksi_jual al = new transaksi_jual();
            al.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_panelpenjuMouseClicked

    private void panelpenjuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelpenjuMouseEntered
        Color randomColor = new Color(255, 200, 78);

        jLabel10.setForeground(randomColor);
        jLabel13.setForeground(randomColor);
        panelpenju.setBackground(Color.WHITE);
    }//GEN-LAST:event_panelpenjuMouseEntered

    private void panelpenjuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelpenjuMouseExited
        Color randomColor2 = new Color(255, 200, 78);

        jLabel10.setForeground(Color.WHITE);
        jLabel13.setForeground(Color.WHITE);
        panelpenju.setBackground(randomColor2);
    }//GEN-LAST:event_panelpenjuMouseExited

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        laporan_beli li = new laporan_beli();
        li.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        Color randomColor = new Color(23, 176, 151);

        jLabel15.setForeground(randomColor);
        jLabel12.setForeground(randomColor);
        panelbeli.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        Color randomColor2 = new Color(23, 176, 151);

        jLabel15.setForeground(Color.WHITE);
        jLabel12.setForeground(Color.WHITE);
        panelbeli.setBackground(randomColor2);
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        laporan_beli li = new laporan_beli();
        li.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        Color randomColor = new Color(23, 176, 151);

        jLabel15.setForeground(randomColor);
        jLabel12.setForeground(randomColor);
        panelbeli.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        Color randomColor2 = new Color(23, 176, 151);

        jLabel15.setForeground(Color.WHITE);
        jLabel12.setForeground(Color.WHITE);
        panelbeli.setBackground(randomColor2);
    }//GEN-LAST:event_jLabel12MouseExited

    private void panelbeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbeliMouseClicked
        laporan_beli li = new laporan_beli();
        li.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelbeliMouseClicked

    private void panelbeliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbeliMouseEntered
        Color randomColor = new Color(23, 176, 151);

        jLabel15.setForeground(randomColor);
        jLabel12.setForeground(randomColor);
        panelbeli.setBackground(Color.WHITE);
    }//GEN-LAST:event_panelbeliMouseEntered

    private void panelbeliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbeliMouseExited
        Color randomColor2 = new Color(23, 176, 151);

        jLabel15.setForeground(Color.WHITE);
        jLabel12.setForeground(Color.WHITE);
        panelbeli.setBackground(randomColor2);
    }//GEN-LAST:event_panelbeliMouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        Color randomColor2 = new Color(255, 200, 78);

        jPanel5.setBackground(randomColor2);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        Color randomColor2 = (Color.WHITE);

        jPanel5.setBackground(randomColor2);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        Color randomColor2 = new Color(255, 200, 78);

        jPanel6.setBackground(randomColor2);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        Color randomColor2 = (Color.WHITE);

        jPanel6.setBackground(randomColor2);
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        Color randomColor2 = new Color(255, 200, 78);

        jPanel4.setBackground(randomColor2);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        Color randomColor2 = (Color.WHITE);

        jPanel4.setBackground(randomColor2);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        Color randomColor2 = new Color(23, 176, 151);

        jPanel7.setBackground(randomColor2);
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        Color randomColor2 = (Color.WHITE);

        jPanel7.setBackground(randomColor2);
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        Color randomColor2 = new Color(23, 176, 151);

        jPanel8.setBackground(randomColor2);
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        Color randomColor2 = (Color.WHITE);

        jPanel8.setBackground(randomColor2);
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        Color randomColor2 = new Color(23, 176, 151);

        jPanel9.setBackground(randomColor2);
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        Color randomColor2 = (Color.WHITE);

        jPanel9.setBackground(randomColor2);
    }//GEN-LAST:event_jPanel9MouseExited

    private void labeltrans7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans7MouseMoved
        labeltrans7.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labeltrans7MouseMoved

    private void labeltrans1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans1MouseMoved
        labeltrans1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labeltrans1MouseMoved

    private void labeltrans11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans11MouseMoved
        labeltrans11.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labeltrans11MouseMoved

    private void labeltrans12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans12MouseMoved
        labeltrans12.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labeltrans12MouseMoved

    private void labeltrans13MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltrans13MouseMoved
        labeltrans13.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labeltrans13MouseMoved

    private void jLabel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseMoved
        jLabel8.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel8MouseMoved

    private void jLabel13MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseMoved
        jLabel13.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel13MouseMoved

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
        jLabel10.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel10MouseMoved

    private void panelpenjuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelpenjuMouseMoved
        panelpenju.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_panelpenjuMouseMoved

    private void jLabel12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseMoved
        jLabel12.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel12MouseMoved

    private void jLabel15MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseMoved
        jLabel15.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel15MouseMoved

    private void panelbeliMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbeliMouseMoved
        panelbeli.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_panelbeliMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labeltrans1;
    private javax.swing.JLabel labeltrans10;
    private javax.swing.JLabel labeltrans11;
    private javax.swing.JLabel labeltrans12;
    private javax.swing.JLabel labeltrans13;
    private javax.swing.JLabel labeltrans7;
    private org.hq.RoundedPanel panelbeli;
    private org.hq.RoundedPanel panelbrg;
    private org.hq.RoundedPanel paneldasbor;
    private org.hq.RoundedPanel panelkrwn;
    private org.hq.RoundedPanel panellap;
    private org.hq.RoundedPanel panellogout;
    private org.hq.RoundedPanel panelpenju;
    private org.hq.RoundedPanel panelsup;
    private org.hq.RoundedPanel paneltransaksi;
    private org.hq.RoundedPanel roundedPanel1;
    private org.hq.RoundedPanel roundedPanel2;
    private org.hq.RoundedPanel roundedPanel3;
    // End of variables declaration//GEN-END:variables
}
