/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elli.shop;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Login2 extends javax.swing.JFrame {

    public void ambildata() {
        //Fungsi untuk menampilkan halaman Dashboard jika memasukkan username dan password 
        //secara benar maka akan muncul notifikasi "Login Sukses" 
        try {
            con = (Connection) Koneksi.configDB();
            Statement s = con.createStatement();
            String query = "SELECT * FROM login WHERE username='" + inputtxt.getText()
                    + "' and password='" + passtxt.getText() + "'";
            ResultSet rs = s.executeQuery(query);

            if (rs.next()) {
                Dashboard2 bor = new Dashboard2();
                bor.setVisible(true);
                this.dispose();
                JOptionPane.showMessageDialog(null, "Login Sukses");

            } else {
                JOptionPane.showMessageDialog(null, "Username atau Password Tidak Sesuai");
            }
        } catch (SQLException ex) {
            System.out.println("error");
        }
    }
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    public Login2() {
        initComponents();
        panellogin.setFocusable(true);
        this.picek.setVisible(false);
        this.line.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panellogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        button_login = new javax.swing.JButton();
        melek = new javax.swing.JLabel();
        picek = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        forgotlabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        line = new javax.swing.JSeparator();
        label_back = new javax.swing.JLabel();
        inputtxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(252, 249, 137));

        jPanel2.setBackground(new java.awt.Color(0, 87, 118));
        jPanel2.setForeground(new java.awt.Color(224, 25, 25));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 87, 118));
        jLabel8.setText("  Aplikasi Pembukuan UMKM");

        jLabel5.setForeground(new java.awt.Color(0, 87, 118));
        jLabel5.setText("   Author k4tifc");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 87, 118));
        jLabel12.setText("   ELLI SHOP");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\iconnew-min (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel13))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel10)
                .addGap(5, 5, 5)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGap(140, 140, 140)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 390, 450));

        panellogin.setBackground(new java.awt.Color(0, 87, 118));
        panellogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        panellogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        panellogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, -1));

        button_login.setBackground(new java.awt.Color(252, 249, 137));
        button_login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button_login.setForeground(new java.awt.Color(0, 87, 118));
        button_login.setText("LOGIN");
        button_login.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_loginMouseMoved(evt);
            }
        });
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });
        panellogin.add(button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 80, 30));

        melek.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\invisible.png")); // NOI18N
        melek.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                melekMouseMoved(evt);
            }
        });
        melek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                melekMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                melekMousePressed(evt);
            }
        });
        panellogin.add(melek, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 30, -1));

        picek.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\visible.png")); // NOI18N
        picek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                picekMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                picekMousePressed(evt);
            }
        });
        panellogin.add(picek, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 30, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(252, 249, 137));
        jLabel4.setText("LOGIN");
        panellogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        forgotlabel.setForeground(new java.awt.Color(252, 249, 137));
        forgotlabel.setText("klik disini");
        forgotlabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                forgotlabelMouseMoved(evt);
            }
        });
        forgotlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotlabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                forgotlabelMousePressed(evt);
            }
        });
        panellogin.add(forgotlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 60, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lupa Password?");
        panellogin.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 100, 30));
        panellogin.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 50, 10));

        label_back.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\back.png")); // NOI18N
        label_back.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                label_backMouseMoved(evt);
            }
        });
        label_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_backMouseClicked(evt);
            }
        });
        panellogin.add(label_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 30, 30));
        panellogin.add(inputtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 180, 30));

        passtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtxtActionPerformed(evt);
            }
        });
        panellogin.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 180, 30));

        getContentPane().add(panellogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 450));

        setSize(new java.awt.Dimension(670, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        ambildata();
    }//GEN-LAST:event_button_loginActionPerformed

    private void melekMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_melekMouseEntered
        picek.setVisible(true);
        melek.setVisible(false);
        passtxt.setEchoChar((char) 0);
    }//GEN-LAST:event_melekMouseEntered

    private void melekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_melekMousePressed

    }//GEN-LAST:event_melekMousePressed

    private void picekMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picekMouseExited
        picek.setVisible(false);
        melek.setVisible(true);
        passtxt.setEchoChar('*');
    }//GEN-LAST:event_picekMouseExited

    private void picekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picekMousePressed

    }//GEN-LAST:event_picekMousePressed

    private void forgotlabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlabelMouseMoved
        forgotlabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_forgotlabelMouseMoved

    private void forgotlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlabelMouseEntered
        line.setVisible(true);
    }//GEN-LAST:event_forgotlabelMouseEntered

    private void forgotlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlabelMouseExited
        line.setVisible(false);
    }//GEN-LAST:event_forgotlabelMouseExited

    private void forgotlabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlabelMousePressed
        //Fungsi untuk menampilkan halaman Lupa Password
        lupa_password sc = new lupa_password();
        this.setVisible(false);
        sc.setVisible(true);
    }//GEN-LAST:event_forgotlabelMousePressed

    private void label_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_backMouseClicked
        opsi_login l = new opsi_login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_label_backMouseClicked

    private void passtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtxtActionPerformed

    private void label_backMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_backMouseMoved
        label_back.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_label_backMouseMoved

    private void melekMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_melekMouseMoved
        picek.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_melekMouseMoved

    private void button_loginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseMoved
        button_login.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_button_loginMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_login;
    private javax.swing.JLabel forgotlabel;
    private javax.swing.JTextField inputtxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel label_back;
    private javax.swing.JSeparator line;
    private javax.swing.JLabel melek;
    private javax.swing.JPanel panellogin;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JLabel picek;
    // End of variables declaration//GEN-END:variables
}
