/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elli.shop;

import elli.shop.Login2;
import elli.shop.Koneksi;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.*;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.swing.JOptionPane;

public class lupa_password extends javax.swing.JFrame {

    public void ambilques() {
        //Fungsi untuk mengambil pertanyaan berdasarkan username yang sudah kita daftarkan diinputkan melalui textfield usertxt
        String username = usertxt.getText();
        try {
            Connection con = (Connection) Koneksi.configDB();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select Pertanyaan from login where username='" + username + "'");
            //Jika Username yang diinputkan benar maka akan muncul juga Pertanyaan dari Usernamenya          
            if (rs.next()) {
                securequestxt.setText(rs.getString(1));
            } //Jika Username yang diinputkan salah maka akan muncul notifikasi peringatan 
            else {
                JOptionPane.showMessageDialog(null, "Please write correct Username");
            }
            con.close();
            rs.close();
        } catch (Exception e) {

        }
    }

    public void ubah_pass() {
        //Fungsi menyimpan perubahan password 
        String username = usertxt.getText();
        String newpass = newpasstxt.getText();
        String Pertanyaan = securequestxt.getText();
        String answer = (String) answertxt.getSelectedItem();

        try {
            Connection con = (Connection) Koneksi.configDB();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from login where username='" + username + "' and Jawaban='" + answer + "'");
            if (rs.next()) //Jika username dan jawaban yang dimasukkan sesuai maka akan muncul notifikasi sandi sukses diupdatesukses
            {
                st.executeUpdate("UPDATE login set password='" + newpass + "' where username='" + username + "' and Jawaban='" + answer + "'");
                JOptionPane.showMessageDialog(null, "Your Password is Succsessfully updated");
                Login2 log = new Login2();
                log.setVisible(true);
                this.dispose();
            } //Jika jawaban yang dimasukkan salah maka akan muncul notifikasi peringatan
            else {
                JOptionPane.showMessageDialog(null, "Please write correct Username or Answer");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    int randomCode;

    public lupa_password() {
        initComponents();
        this.picek.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        roundedPanel1 = new org.hq.RoundedPanel();
        roundedPanel2 = new org.hq.RoundedPanel();
        jPanel4 = new javax.swing.JPanel();
        usertxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newpasstxt = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        melek = new javax.swing.JLabel();
        picek = new javax.swing.JLabel();
        answertxt = new javax.swing.JComboBox<>();
        questxt = new javax.swing.JScrollPane();
        securequestxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Lupa? Ingat Pertanyaanmu?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 360, -1));

        roundedPanel1.setBackground(new java.awt.Color(0, 87, 118));
        roundedPanel1.setRoundBottomLeft(10);
        roundedPanel1.setRoundBottomRight(10);
        roundedPanel1.setRoundTopLeft(10);
        roundedPanel1.setRoundTopRight(10);

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 10));

        roundedPanel2.setBackground(new java.awt.Color(252, 249, 137));
        roundedPanel2.setRoundBottomLeft(10);
        roundedPanel2.setRoundBottomRight(10);
        roundedPanel2.setRoundTopLeft(10);
        roundedPanel2.setRoundTopRight(10);

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(roundedPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 100));

        jPanel4.setBackground(new java.awt.Color(0, 87, 118));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 140, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 249, 137));
        jLabel1.setText("Username");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 249, 137));
        jLabel2.setText("Security Question");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(252, 249, 137));
        jLabel4.setText("Answer");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(252, 249, 137));
        jLabel5.setText("New Password");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel4.add(newpasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 170, -1));

        jButton1.setBackground(new java.awt.Color(252, 249, 137));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 87, 118));
        jButton1.setText("Cari");
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jButton2.setBackground(new java.awt.Color(252, 249, 137));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 87, 118));
        jButton2.setText("Save");
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 70, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Batal");
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        melek.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\invisible.png")); // NOI18N
        melek.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                melekMouseMoved(evt);
            }
        });
        melek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                melekMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                melekMousePressed(evt);
            }
        });
        jPanel4.add(melek, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 30, 30));

        picek.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\visible.png")); // NOI18N
        picek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                picekMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                picekMousePressed(evt);
            }
        });
        jPanel4.add(picek, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, 30));

        answertxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hijau", "Merah", "Kuning", "SD", "SMP", "SMA" }));
        jPanel4.add(answertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 220, -1));

        securequestxt.setColumns(20);
        securequestxt.setRows(5);
        questxt.setViewportView(securequestxt);

        jPanel4.add(questxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 220, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 440, 300));

        setSize(new java.awt.Dimension(440, 401));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ambilques();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ubah_pass();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Fungsi untuk kembali ke halaman Login
        Login2 log = new Login2();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void melekMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_melekMouseEntered
        picek.setVisible(true);
        melek.setVisible(false);
        newpasstxt.setEchoChar((char) 0);
    }//GEN-LAST:event_melekMouseEntered

    private void melekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_melekMousePressed

    }//GEN-LAST:event_melekMousePressed

    private void picekMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picekMouseExited
        melek.setVisible(true);
        picek.setVisible(false);
        newpasstxt.setEchoChar('*');
    }//GEN-LAST:event_picekMouseExited

    private void picekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picekMousePressed

    }//GEN-LAST:event_picekMousePressed

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        jButton3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        jButton2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton2MouseMoved

    private void melekMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_melekMouseMoved
        picek.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_melekMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lupa_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lupa_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lupa_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lupa_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lupa_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> answertxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel melek;
    private javax.swing.JPasswordField newpasstxt;
    private javax.swing.JLabel picek;
    private javax.swing.JScrollPane questxt;
    private org.hq.RoundedPanel roundedPanel1;
    private org.hq.RoundedPanel roundedPanel2;
    private javax.swing.JTextArea securequestxt;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
