/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elli.shop;

import elli.shop.Register;
import elli.shop.RFID_login;
import elli.shop.Login2;
import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author ACER
 */
public class opsi_login extends javax.swing.JFrame {

    /**
     * Creates new form opsi_login
     */
    public opsi_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new org.hq.RoundedPanel();
        roundedPanel2 = new org.hq.RoundedPanel();
        panelrfid = new org.hq.RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        panellogin = new org.hq.RoundedPanel();
        labellogin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panelx = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelmin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelregister = new org.hq.RoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel1.setBackground(new java.awt.Color(0, 87, 118));
        roundedPanel1.setRoundBottomLeft(25);
        roundedPanel1.setRoundTopRight(25);
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 148, -1, -1));

        roundedPanel2.setBackground(new java.awt.Color(0, 87, 118));
        roundedPanel2.setRoundBottomRight(25);
        roundedPanel2.setRoundTopLeft(25);
        roundedPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(roundedPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 148, -1, -1));

        panelrfid.setBackground(new java.awt.Color(0, 87, 118));
        panelrfid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        panelrfid.setRoundBottomRight(50);
        panelrfid.setRoundTopLeft(50);
        panelrfid.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelrfidMouseMoved(evt);
            }
        });
        panelrfid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelrfidMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelrfidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelrfidMouseExited(evt);
            }
        });
        panelrfid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 249, 137));
        jLabel2.setText("Login RFID");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        panelrfid.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel1.add(panelrfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 160, 110));

        panellogin.setBackground(new java.awt.Color(0, 87, 118));
        panellogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        panellogin.setRoundBottomLeft(50);
        panellogin.setRoundTopRight(50);
        panellogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelloginMouseMoved(evt);
            }
        });
        panellogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelloginMouseExited(evt);
            }
        });
        panellogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labellogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labellogin.setForeground(new java.awt.Color(252, 249, 137));
        labellogin.setText("Login Manual");
        labellogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelloginMouseMoved(evt);
            }
        });
        labellogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelloginMouseExited(evt);
            }
        });
        panellogin.add(labellogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel1.add(panellogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 170, 110));

        jPanel3.setBackground(new java.awt.Color(252, 249, 137));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 670, 10));

        jPanel4.setBackground(new java.awt.Color(0, 87, 118));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 670, 10));

        panelx.setBackground(new java.awt.Color(255, 255, 255));
        panelx.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelxMouseMoved(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("X");
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel6MouseMoved(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelxLayout = new javax.swing.GroupLayout(panelx);
        panelx.setLayout(panelxLayout);
        panelxLayout.setHorizontalGroup(
            panelxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelxLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelxLayout.setVerticalGroup(
            panelxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelxLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelx, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, 30));

        panelmin.setBackground(new java.awt.Color(255, 255, 255));
        panelmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelminMouseMoved(evt);
            }
        });
        panelmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelminMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("—");
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelminLayout = new javax.swing.GroupLayout(panelmin);
        panelmin.setLayout(panelminLayout);
        panelminLayout.setHorizontalGroup(
            panelminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelminLayout.setVerticalGroup(
            panelminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelminLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 30, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\iconnew-min (1).png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 87, 118));

        panelregister.setBackground(new java.awt.Color(0, 87, 118));
        panelregister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        panelregister.setAutoscrolls(true);
        panelregister.setRoundBottomLeft(50);
        panelregister.setRoundBottomRight(50);
        panelregister.setRoundTopLeft(50);
        panelregister.setRoundTopRight(50);
        panelregister.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelregisterMouseMoved(evt);
            }
        });
        panelregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelregisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelregisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelregisterMouseExited(evt);
            }
        });
        panelregister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(252, 249, 137));
        jLabel3.setText("Akun");
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        panelregister.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(252, 249, 137));
        jLabel4.setText("Registrasi ");
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        panelregister.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(panelregister, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(panelregister, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 650, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 450));

        setSize(new java.awt.Dimension(670, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelloginMouseEntered
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        labellogin.setForeground(randomColor2);
        panellogin.setBackground(randomColor);
    }//GEN-LAST:event_labelloginMouseEntered

    private void labelloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelloginMouseExited
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        labellogin.setForeground(randomColor);
        panellogin.setBackground(randomColor2);
    }//GEN-LAST:event_labelloginMouseExited

    private void labelloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelloginMouseClicked
        Login2 l = new Login2();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelloginMouseClicked

    private void panelloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelloginMouseEntered
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        labellogin.setForeground(randomColor2);
        panellogin.setBackground(randomColor);
    }//GEN-LAST:event_panelloginMouseEntered

    private void panelloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelloginMouseExited
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        labellogin.setForeground(randomColor);
        panellogin.setBackground(randomColor2);
    }//GEN-LAST:event_panelloginMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        jLabel2.setForeground(randomColor2);
        panelrfid.setBackground(randomColor);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        jLabel2.setForeground(randomColor);
        panelrfid.setBackground(randomColor2);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        RFID_login r = new RFID_login();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void panelloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelloginMouseClicked
        Login2 l = new Login2();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelloginMouseClicked

    private void panelrfidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelrfidMouseEntered
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        jLabel2.setForeground(randomColor2);
        panelrfid.setBackground(randomColor);
    }//GEN-LAST:event_panelrfidMouseEntered

    private void panelrfidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelrfidMouseExited
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        jLabel2.setForeground(randomColor);
        panelrfid.setBackground(randomColor2);
    }//GEN-LAST:event_panelrfidMouseExited

    private void panelrfidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelrfidMouseClicked
        RFID_login r = new RFID_login();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelrfidMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Register re = new Register();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        jLabel4.setForeground(randomColor2);
        jLabel3.setForeground(randomColor2);
        panelregister.setBackground(randomColor);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        jLabel4.setForeground(randomColor);
        jLabel3.setForeground(randomColor);
        panelregister.setBackground(randomColor2);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Register re = new Register();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        jLabel3.setForeground(randomColor2);
        jLabel4.setForeground(randomColor2);
        panelregister.setBackground(randomColor);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        jLabel4.setForeground(randomColor);
        jLabel3.setForeground(randomColor);
        panelregister.setBackground(randomColor2);
    }//GEN-LAST:event_jLabel3MouseExited

    private void panelregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelregisterMouseClicked
        Register re = new Register();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelregisterMouseClicked

    private void panelregisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelregisterMouseEntered
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        jLabel4.setForeground(randomColor2);
        jLabel3.setForeground(randomColor2);
        panelregister.setBackground(randomColor);
    }//GEN-LAST:event_panelregisterMouseEntered

    private void panelregisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelregisterMouseExited
        Color randomColor = new Color(252, 249, 137);
        Color randomColor2 = new Color(0, 87, 118);

        jLabel4.setForeground(randomColor);
        jLabel3.setForeground(randomColor);
        panelregister.setBackground(randomColor2);
    }//GEN-LAST:event_panelregisterMouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        panelx.setBackground(Color.RED);
        jLabel6.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        panelx.setBackground(Color.WHITE);
        jLabel6.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        panelmin.setBackground(Color.BLACK);
        jLabel7.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        panelmin.setBackground(Color.WHITE);
        jLabel7.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel7MouseExited

    private void panelminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelminMouseEntered

    private void panelminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelminMouseExited

    private void labelloginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelloginMouseMoved
        labellogin.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labelloginMouseMoved

    private void panelloginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelloginMouseMoved
        panellogin.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_panelloginMouseMoved

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        jLabel2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel2MouseMoved

    private void panelrfidMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelrfidMouseMoved
        panelrfid.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_panelrfidMouseMoved

    private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved
        jLabel4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel4MouseMoved

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        jLabel3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel3MouseMoved

    private void panelregisterMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelregisterMouseMoved
        panelregister.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_panelregisterMouseMoved

    private void jLabel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseMoved
        jLabel6.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel6MouseMoved

    private void panelxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelxMouseMoved
        panelx.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_panelxMouseMoved

    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
        jLabel7.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel7MouseMoved

    private void panelminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelminMouseMoved
        panelmin.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_panelminMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opsi_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opsi_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opsi_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opsi_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new opsi_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labellogin;
    private org.hq.RoundedPanel panellogin;
    private javax.swing.JPanel panelmin;
    private org.hq.RoundedPanel panelregister;
    private org.hq.RoundedPanel panelrfid;
    private javax.swing.JPanel panelx;
    private org.hq.RoundedPanel roundedPanel1;
    private org.hq.RoundedPanel roundedPanel2;
    // End of variables declaration//GEN-END:variables
}
